/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Controlador.AccesoAleatorio;
import Controlador.AccesoAleatorio;
import Controlador.Conector;
import Controlador.PreferenciasGenerador;
import Modelo.Tabla;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author oracle
 */
public class Generador extends javax.swing.JFrame {

    /**
     * Creates new form Generador
     */
    static final int MAXTABLAS = 10000;
    static final int MAXEXCEPCIONES = 25;
    static final int MAXBINGO = 25;
    static final int MAXWTABLA = 4;
    static final int MAXVECTOR = 5;
    
    private updPassword winUpdPassword;

    private int MaxTablas;
    private int nObligatorios;
    private int codigoTablas = 1;
    private int[] excNum;
    private int[] wTabla;
    private int[] vector;
    private int[] bingo;
    private int[] bingo_w;
    
    private int[] tmpWtabla;

    private int[][] Tablas;

    private Conector con;

    private PreferenciasGenerador prefs;

    public Generador() throws IOException {
        int i, j;
        initComponents();
        this.setLocationRelativeTo(null);

        // Preferencias persistentes: que modos de generacion se le ofrecen al
        // operador (solo Normal, solo Personalizada o ambas).
        prefs = new PreferenciasGenerador();
        aplicarModosDisponibles();

        // Gesto oculto: Ctrl+Shift+DobleClic sobre el rotulo "TABLAS A GENERAR"
        // abre la ventana de opciones de generacion.
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2 && e.isControlDown() && e.isShiftDown()) {
                    abrirOpcionesGeneracion();
                }
            }
        });

        
        winUpdPassword = new updPassword();
        
        winUpdPassword.setVisible(false);
        


        con = new Conector();
        con.connect();

        MaxTablas = 0;

        excNum = new int[MAXEXCEPCIONES];
        for (i = 0; i < MAXEXCEPCIONES; i++) {
            excNum[i] = 0;
        }

        wTabla = new int[MAXWTABLA];
        for (i = 0; i < MAXWTABLA; i++) {
            wTabla[i] = 0;
        }

        vector = new int[MAXVECTOR];
        for (i = 0; i < MAXVECTOR; i++) {
            vector[i] = 0;
        }

        bingo = new int[MAXBINGO];
        for (i = 0; i < MAXBINGO; i++) {
            bingo[i] = 0;
        }
        
        bingo_w = new int[MAXBINGO];
        for (i = 0; i < MAXBINGO; i++) {
            bingo_w[i] = 0;
        }
        
        
        /*
        Tablas = new int[this.][MAXBINGO+1];
        for ( i=0; i<MAXTABLAS; i++ )
            for ( j=0; j<MAXBINGO+1; j++ )
                Tablas[i][j]=0;   
         */

        if (!AccesoAleatorio.buscarFile(new File(AccesoAleatorio.getRutaFileDB() + "tablas.db"))) {
            System.out.print("Error de Conexion a Base de Datos");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.ButtonGroup();
        BingoCodificacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        N1 = new javax.swing.JTextField();
        N2 = new javax.swing.JTextField();
        N3 = new javax.swing.JTextField();
        N4 = new javax.swing.JTextField();
        N5 = new javax.swing.JTextField();
        N6 = new javax.swing.JTextField();
        N7 = new javax.swing.JTextField();
        N8 = new javax.swing.JTextField();
        N9 = new javax.swing.JTextField();
        N10 = new javax.swing.JTextField();
        N11 = new javax.swing.JTextField();
        N12 = new javax.swing.JTextField();
        N13 = new javax.swing.JTextField();
        N14 = new javax.swing.JTextField();
        N15 = new javax.swing.JTextField();
        N16 = new javax.swing.JTextField();
        N17 = new javax.swing.JTextField();
        N18 = new javax.swing.JTextField();
        N19 = new javax.swing.JTextField();
        N20 = new javax.swing.JTextField();
        N21 = new javax.swing.JTextField();
        N22 = new javax.swing.JTextField();
        N23 = new javax.swing.JTextField();
        N24 = new javax.swing.JTextField();
        N25 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nExcepciones = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        WT1 = new javax.swing.JTextField();
        WT2 = new javax.swing.JTextField();
        WT3 = new javax.swing.JTextField();
        WT4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NTablas = new javax.swing.JTextField();
        juegoNormal = new javax.swing.JRadioButton();
        juegoCustom = new javax.swing.JRadioButton();
        btnGenerar = new javax.swing.JButton();
        btn_updPassword = new javax.swing.JButton();
        btn_SalirGenerador = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BingoNumeros = new javax.swing.JRadioButton();
        BingoLetras = new javax.swing.JRadioButton();
        BingoNumerosLetras = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador");
        setName("Generador"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        N1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N1.setText("0");
        N1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N1.setMaximumSize(new java.awt.Dimension(2, 2));

        N2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N2.setText("0");
        N2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N2.setMaximumSize(new java.awt.Dimension(2, 2));
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });

        N3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N3.setText("0");
        N3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N3.setMaximumSize(new java.awt.Dimension(2, 2));

        N4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N4.setText("0");
        N4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N4.setMaximumSize(new java.awt.Dimension(2, 2));

        N5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N5.setText("0");
        N5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N5.setMaximumSize(new java.awt.Dimension(2, 2));

        N6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N6.setText("0");
        N6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N6.setMaximumSize(new java.awt.Dimension(2, 2));

        N7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N7.setText("0");
        N7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N7.setMaximumSize(new java.awt.Dimension(2, 2));

        N8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N8.setText("0");
        N8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N8.setMaximumSize(new java.awt.Dimension(2, 2));

        N9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N9.setText("0");
        N9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N9.setMaximumSize(new java.awt.Dimension(2, 2));

        N10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N10.setText("0");
        N10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N10.setMaximumSize(new java.awt.Dimension(2, 2));

        N11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N11.setText("0");
        N11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N11.setMaximumSize(new java.awt.Dimension(2, 2));

        N12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N12.setText("0");
        N12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N12.setMaximumSize(new java.awt.Dimension(2, 2));

        N13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N13.setText("0");
        N13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N13.setMaximumSize(new java.awt.Dimension(2, 2));

        N14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N14.setText("0");
        N14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N14.setMaximumSize(new java.awt.Dimension(2, 2));

        N15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N15.setText("0");
        N15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N15.setMaximumSize(new java.awt.Dimension(2, 2));

        N16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N16.setText("0");
        N16.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N16.setMaximumSize(new java.awt.Dimension(2, 2));

        N17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N17.setText("0");
        N17.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N17.setMaximumSize(new java.awt.Dimension(2, 2));

        N18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N18.setText("0");
        N18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N18.setMaximumSize(new java.awt.Dimension(2, 2));

        N19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N19.setText("0");
        N19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N19.setMaximumSize(new java.awt.Dimension(2, 2));

        N20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N20.setText("0");
        N20.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N20.setMaximumSize(new java.awt.Dimension(2, 2));

        N21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N21.setText("0");
        N21.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N21.setMaximumSize(new java.awt.Dimension(2, 2));

        N22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N22.setText("0");
        N22.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N22.setMaximumSize(new java.awt.Dimension(2, 2));

        N23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N23.setText("0");
        N23.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N23.setMaximumSize(new java.awt.Dimension(2, 2));

        N24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N24.setText("0");
        N24.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N24.setMaximumSize(new java.awt.Dimension(2, 2));

        N25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        N25.setText("0");
        N25.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        N25.setMaximumSize(new java.awt.Dimension(2, 2));

        jLabel1.setText("POR LO MENOS");

        nExcepciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nExcepciones.setText("0");
        nExcepciones.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nExcepciones.setMaximumSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nExcepciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(N6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(N11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(N16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(N21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nExcepciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("TABLAS GANADORAS");

        WT1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        WT1.setText("0");
        WT1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WT1.setMaximumSize(new java.awt.Dimension(2, 2));

        WT2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        WT2.setText("0");
        WT2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WT2.setMaximumSize(new java.awt.Dimension(2, 2));

        WT3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        WT3.setText("0");
        WT3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WT3.setMaximumSize(new java.awt.Dimension(2, 2));

        WT4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        WT4.setText("0");
        WT4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WT4.setMaximumSize(new java.awt.Dimension(2, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WT1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WT2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WT3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WT4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WT2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WT3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WT4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("TABLAS A GENERAR");

        NTablas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NTablas.setText("0");
        NTablas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NTablas.setMaximumSize(new java.awt.Dimension(2, 2));
        NTablas.setName(""); // NOI18N

        Juego.add(juegoNormal);
        juegoNormal.setText("Normal");
        juegoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoNormalActionPerformed(evt);
            }
        });

        Juego.add(juegoCustom);
        juegoCustom.setText("Personalizado");
        juegoCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoCustomActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(juegoNormal)
                            .addComponent(juegoCustom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnGenerar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(juegoNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(juegoCustom))
                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_updPassword.setText("Cambiar Contraseña");
        btn_updPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updPasswordActionPerformed(evt);
            }
        });

        btn_SalirGenerador.setText("Salir");
        btn_SalirGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirGeneradorActionPerformed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("NUMERACION DE TABLAS");

        BingoCodificacion.add(BingoNumeros);
        BingoNumeros.setText("Numeros");
        BingoNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingoNumerosActionPerformed(evt);
            }
        });

        BingoCodificacion.add(BingoLetras);
        BingoLetras.setText("Letras");
        BingoLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingoLetrasActionPerformed(evt);
            }
        });

        BingoCodificacion.add(BingoNumerosLetras);
        BingoNumerosLetras.setText("Numeros y Letras");
        BingoNumerosLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingoNumerosLetrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BingoNumerosLetras)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(BingoNumeros)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BingoLetras))
                        .addComponent(jLabel4)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BingoNumeros)
                    .addComponent(BingoLetras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BingoNumerosLetras)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_updPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_SalirGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updPassword)
                    .addComponent(btn_SalirGenerador))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la ventana oculta de opciones de generacion y, si el administrador
     * guardo, aplica de inmediato lo elegido.
     */
    private void abrirOpcionesGeneracion() {
        OpcionesGeneracion dlg = new OpcionesGeneracion(this, prefs);
        dlg.setVisible(true);
        if (dlg.isAceptado()) {
            aplicarModosDisponibles();
        }
    }

    /**
     * Deja a la vista solo los modos de generacion habilitados en las
     * preferencias. Si queda uno solo, se selecciona de una vez (y se muestran u
     * ocultan los paneles de Excepciones y Tablas Ganadoras segun corresponda).
     */
    private void aplicarModosDisponibles() {
        String modos = prefs.getModosDisponibles();
        boolean verNormal = !PreferenciasGenerador.MODO_PERSONALIZADA.equals(modos);
        boolean verCustom = !PreferenciasGenerador.MODO_NORMAL.equals(modos);

        juegoNormal.setVisible(verNormal);
        juegoCustom.setVisible(verCustom);

        // No dejar seleccionado un modo que ya no esta disponible.
        if ((!verNormal && juegoNormal.isSelected()) || (!verCustom && juegoCustom.isSelected())) {
            Juego.clearSelection();
        }

        if (verNormal && !verCustom) {
            juegoNormal.setSelected(true);
            jPanel1.setVisible(false);
            jPanel2.setVisible(false);
        } else if (verCustom && !verNormal) {
            juegoCustom.setSelected(true);
            jPanel1.setVisible(true);
            jPanel2.setVisible(true);
        }

        jPanel3.revalidate();
        jPanel3.repaint();
    }

    private void juegoCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoCustomActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(true);

    }//GEN-LAST:event_juegoCustomActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        Date fi = new Date();
        if (NTablas.getText().isEmpty() /* Verificar si es diferente de cero 0*/) {
            JOptionPane.showMessageDialog(this, "¡Debe diligenciar el Numero de Tablas.!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            MaxTablas = Integer.parseInt(NTablas.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero para Numero de Tablas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (juegoNormal.isSelected()) {
            try {
                /* Juego Normal*/
 /*Generar Tablas*/

                con.borrarBase();
                GenerarTablas(1);
                //Mensaje.setText(Integer.toString(this.generarNumero(1)));
            } catch (IOException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (juegoCustom.isSelected()) {

                if (nExcepciones.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "¡Debe diligenciar el Numero de Excepciones.!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                try {
                    nObligatorios = Integer.parseInt(nExcepciones.getText());
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un número entero para Excepciones.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (WT1.getText().isEmpty() || WT2.getText().isEmpty() || WT3.getText().isEmpty() || WT4.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "¡Debe diligenciar al menos una Tablas Ganadora.!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                try {
                    wTabla[0] = Integer.parseInt(WT1.getText());
                    wTabla[1] = Integer.parseInt(WT2.getText());
                    wTabla[2] = Integer.parseInt(WT3.getText());
                    wTabla[3] = Integer.parseInt(WT4.getText());
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un número entero Numero de Tablas.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (N1.getText().isEmpty() || N2.getText().isEmpty() || N3.getText().isEmpty() || N4.getText().isEmpty() || N5.getText().isEmpty()
                        || N6.getText().isEmpty() || N7.getText().isEmpty() || N8.getText().isEmpty() || N9.getText().isEmpty() || N10.getText().isEmpty()
                        || N11.getText().isEmpty() || N12.getText().isEmpty() || N13.getText().isEmpty() || N14.getText().isEmpty() || N15.getText().isEmpty()
                        || N16.getText().isEmpty() || N17.getText().isEmpty() || N18.getText().isEmpty() || N19.getText().isEmpty() || N20.getText().isEmpty()
                        || N21.getText().isEmpty() || N22.getText().isEmpty() || N23.getText().isEmpty() || N24.getText().isEmpty() || N25.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "¡Debe diligenciar al menos una Excepcion.!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                try {
                    excNum[0] = Integer.parseInt(N1.getText());
                    excNum[1] = Integer.parseInt(N2.getText());
                    excNum[2] = Integer.parseInt(N3.getText());
                    excNum[3] = Integer.parseInt(N4.getText());
                    excNum[5] = Integer.parseInt(N5.getText());
                    excNum[6] = Integer.parseInt(N6.getText());
                    excNum[7] = Integer.parseInt(N7.getText());
                    excNum[8] = Integer.parseInt(N8.getText());
                    excNum[9] = Integer.parseInt(N9.getText());
                    excNum[10] = Integer.parseInt(N10.getText());
                    excNum[11] = Integer.parseInt(N11.getText());
                    excNum[12] = Integer.parseInt(N12.getText());
                    excNum[13] = Integer.parseInt(N13.getText());
                    excNum[14] = Integer.parseInt(N14.getText());
                    excNum[15] = Integer.parseInt(N15.getText());
                    excNum[16] = Integer.parseInt(N16.getText());
                    excNum[17] = Integer.parseInt(N17.getText());
                    excNum[18] = Integer.parseInt(N18.getText());
                    excNum[19] = Integer.parseInt(N19.getText());
                    excNum[20] = Integer.parseInt(N20.getText());
                    excNum[21] = Integer.parseInt(N21.getText());
                    excNum[22] = Integer.parseInt(N22.getText());
                    excNum[23] = Integer.parseInt(N23.getText());
                    excNum[24] = Integer.parseInt(N24.getText());
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar un número entero Numero en Excepciones.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                try {
                    con.borrarBase();
                    GenerarTablas(2);
                } catch (IOException | SQLException ex) {
                    Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe Seleccionar una opcion (Norma / Personalizado).", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void juegoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoNormalActionPerformed
        // TODO add your handling code here:

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);


    }//GEN-LAST:event_juegoNormalActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        con.close();
    }//GEN-LAST:event_formWindowClosed

    private void btn_SalirGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirGeneradorActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirGeneradorActionPerformed

    private void btn_updPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updPasswordActionPerformed
        // TODO add your handling code here:
        
        
        winUpdPassword.setVisible(true);
    }//GEN-LAST:event_btn_updPasswordActionPerformed

    private void BingoNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingoNumerosActionPerformed
        // TODO add your handling code here:
        codigoTablas = 1;
    }//GEN-LAST:event_BingoNumerosActionPerformed

    private void BingoLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingoLetrasActionPerformed
        // TODO add your handling code here:
        codigoTablas = 2;
    }//GEN-LAST:event_BingoLetrasActionPerformed

    private void BingoNumerosLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingoNumerosLetrasActionPerformed
        // TODO add your handling code here:
        codigoTablas = 3;
    }//GEN-LAST:event_BingoNumerosLetrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BingoCodificacion;
    private javax.swing.JRadioButton BingoLetras;
    private javax.swing.JRadioButton BingoNumeros;
    private javax.swing.JRadioButton BingoNumerosLetras;
    private javax.swing.ButtonGroup Juego;
    private javax.swing.JTextField N1;
    private javax.swing.JTextField N10;
    private javax.swing.JTextField N11;
    private javax.swing.JTextField N12;
    private javax.swing.JTextField N13;
    private javax.swing.JTextField N14;
    private javax.swing.JTextField N15;
    private javax.swing.JTextField N16;
    private javax.swing.JTextField N17;
    private javax.swing.JTextField N18;
    private javax.swing.JTextField N19;
    private javax.swing.JTextField N2;
    private javax.swing.JTextField N20;
    private javax.swing.JTextField N21;
    private javax.swing.JTextField N22;
    private javax.swing.JTextField N23;
    private javax.swing.JTextField N24;
    private javax.swing.JTextField N25;
    private javax.swing.JTextField N3;
    private javax.swing.JTextField N4;
    private javax.swing.JTextField N5;
    private javax.swing.JTextField N6;
    private javax.swing.JTextField N7;
    private javax.swing.JTextField N8;
    private javax.swing.JTextField N9;
    private javax.swing.JTextField NTablas;
    private javax.swing.JTextField WT1;
    private javax.swing.JTextField WT2;
    private javax.swing.JTextField WT3;
    private javax.swing.JTextField WT4;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btn_SalirGenerador;
    private javax.swing.JButton btn_updPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton juegoCustom;
    private javax.swing.JRadioButton juegoNormal;
    private javax.swing.JTextField nExcepciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //con = new Conector();

        // Create and display the form 
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Generador().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    public void GenerarTablas(int Opcion) throws IOException, SQLException {

        boolean pasa;
        pasa = false;
        switch (Opcion) {
            case 1:

                for (int idx = 0; idx < this.MaxTablas; idx++) {

                    pasa = false;
                    //AccesoAleatorio.crearFileTablas( new File("/oracle/ssipc/LAC/Bingo/Tablas.dat") );
                    do {
                        this.generarVector("B");
                        System.arraycopy(vector, 0, bingo, 0, 5);
                        this.generarVector("I");
                        System.arraycopy(vector, 0, bingo, 5, 5);
                        this.generarVector("N");
                        System.arraycopy(vector, 0, bingo, 10, 5);
                        this.generarVector("G");
                        System.arraycopy(vector, 0, bingo, 15, 5);
                        this.generarVector("O");
                        System.arraycopy(vector, 0, bingo, 20, 5);

                        if (con.buscarTabla(bingo) != -1) {
                            
                            con.saveTabla(new Tabla(idx + 1, true,
                                    bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                    bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                    bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                    bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                    bingo[20], bingo[21], bingo[22], bingo[23], bingo[24] ),codigoTablas);

                            pasa = true;

                        }
                    } while (!pasa);
                    //AccesoAleatorio.cerrar();
                }
                
                
                JOptionPane.showMessageDialog(this, "Tablas Generadas", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2:

                /*Inicializar semilla para el Random*/
                //AccesoAleatorio.crearFileTablas( new File("/oracle/ssipc/LAC/Bingo/Tablas.dat") );
                for (int idx = 0; idx < this.MaxTablas; idx++) {
                    if (this.wTabla[0] == idx + 1) {
                        pasa = false;
                        do {
                            this.generarVector("B");
                            System.arraycopy(vector, 0, bingo, 0, 5);
                            this.generarVector("I");
                            System.arraycopy(vector, 0, bingo, 5, 5);
                            this.generarVector("N");
                            System.arraycopy(vector, 0, bingo, 10, 5);
                            this.generarVector("G");
                            System.arraycopy(vector, 0, bingo, 15, 5);
                            this.generarVector("O");
                            System.arraycopy(vector, 0, bingo, 20, 5);
                            if (this.numGeneradosExcepcion() == 0) {
                                if (con.buscarTabla(bingo) != -1) {
                                    
                                    con.saveTabla(new Tabla(idx + 1, true,
                                            bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                            bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                            bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                            bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                            bingo[20], bingo[21], bingo[22], bingo[23], bingo[24]), codigoTablas);
                                    pasa = true;
                                }
                            }
                        } while (!pasa);
                        
                        bingo_w[0]=bingo[0];
                        bingo_w[1]=bingo[1];
                        bingo_w[2]=bingo[2];
                        bingo_w[3]=bingo[3];
                        bingo_w[4]=bingo[4];
                        bingo_w[5]=bingo[5];
                        bingo_w[6]=bingo[6];
                        bingo_w[7]=bingo[7];
                        bingo_w[8]=bingo[8];
                        bingo_w[9]=bingo[9];
                        bingo_w[10]=bingo[10];
                        bingo_w[11]=bingo[11];
                        bingo_w[12]=bingo[12];
                        bingo_w[13]=bingo[13];
                        bingo_w[14]=bingo[14];
                        bingo_w[15]=bingo[15];
                        bingo_w[16]=bingo[16];
                        bingo_w[17]=bingo[17];
                        bingo_w[18]=bingo[18];
                        bingo_w[19]=bingo[19];
                        bingo_w[20]=bingo[20];
                        bingo_w[21]=bingo[21];
                        bingo_w[22]=bingo[22];
                        bingo_w[23]=bingo[23];
                        bingo_w[24]=bingo[24]; 
                        
                        
                        
                        
                    } else if (this.wTabla[1] == idx + 1) {
                        pasa = true;
                        //Segunda Tabala Ganadora
                        bingo[0]=bingo_w[4];
                        bingo[1]=bingo_w[3];
                        bingo[2]=bingo_w[0];
                        bingo[3]=bingo_w[1];
                        bingo[4]=bingo_w[2];
                        bingo[5]=bingo_w[7];
                        bingo[6]=bingo_w[9];
                        bingo[7]=bingo_w[5];
                        bingo[8]=bingo_w[6];
                        bingo[9]=bingo_w[8];
                        bingo[10]=bingo_w[11];
                        bingo[11]=bingo_w[14];
                        bingo[12]=bingo_w[12];
                        bingo[13]=bingo_w[10];
                        bingo[14]=bingo_w[13];
                        bingo[15]=bingo_w[15];
                        bingo[16]=bingo_w[17];
                        bingo[17]=bingo_w[19];
                        bingo[18]=bingo_w[16];
                        bingo[19]=bingo_w[18];
                        bingo[20]=bingo_w[22];
                        bingo[21]=bingo_w[20];
                        bingo[22]=bingo_w[24];
                        bingo[23]=bingo_w[23];
                        bingo[24]=bingo_w[21];   
                        con.saveTabla(new Tabla(idx + 1, true,
                                            bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                            bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                            bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                            bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                            bingo[20], bingo[21], bingo[22], bingo[23], bingo[24] ), codigoTablas);
                        
                    } else if (this.wTabla[2] == idx + 1) {
                          pasa = true;

                        //Tercera Tabla Ganadora
                        bingo[0]=bingo_w[1];
                        bingo[1]=bingo_w[0];
                        bingo[2]=bingo_w[2];
                        bingo[3]=bingo_w[4];
                        bingo[4]=bingo_w[3];
                        bingo[5]=bingo_w[9];
                        bingo[6]=bingo_w[7];
                        bingo[7]=bingo_w[8];
                        bingo[8]=bingo_w[6];
                        bingo[9]=bingo_w[5];
                        bingo[10]=bingo_w[14];
                        bingo[11]=bingo_w[13];
                        bingo[12]=bingo_w[12];
                        bingo[13]=bingo_w[10];
                        bingo[14]=bingo_w[11];
                        bingo[15]=bingo_w[17];
                        bingo[16]=bingo_w[18];
                        bingo[17]=bingo_w[16];
                        bingo[18]=bingo_w[19];
                        bingo[19]=bingo_w[15];
                        bingo[20]=bingo_w[22];
                        bingo[21]=bingo_w[21];
                        bingo[22]=bingo_w[24];
                        bingo[23]=bingo_w[23];
                        bingo[24]=bingo_w[20];
                        con.saveTabla(new Tabla(idx + 1, true,
                                            bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                            bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                            bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                            bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                            bingo[20], bingo[21], bingo[22], bingo[23], bingo[24] ),codigoTablas);
                        
                        
                        
                    } else if (this.wTabla[3] == idx + 1) {
                        //Cuarta Tabla Ganadora
                        bingo[0]=bingo_w[3];
                        bingo[1]=bingo_w[1];
                        bingo[2]=bingo_w[2];
                        bingo[3]=bingo_w[0];
                        bingo[4]=bingo_w[4];
                        bingo[5]=bingo_w[8];
                        bingo[6]=bingo_w[6];
                        bingo[7]=bingo_w[5];
                        bingo[8]=bingo_w[7];
                        bingo[9]=bingo_w[9];
                        bingo[10]=bingo_w[14];
                        bingo[11]=bingo_w[10];
                        bingo[12]=bingo_w[12];
                        bingo[13]=bingo_w[11];
                        bingo[14]=bingo_w[13];
                        bingo[15]=bingo_w[18];
                        bingo[16]=bingo_w[16];
                        bingo[17]=bingo_w[17];
                        bingo[18]=bingo_w[15];
                        bingo[19]=bingo_w[19];
                        bingo[20]=bingo_w[23];
                        bingo[21]=bingo_w[22];
                        bingo[22]=bingo_w[21];
                        bingo[23]=bingo_w[20];
                        bingo[24]=bingo_w[24];
                        con.saveTabla(new Tabla(idx + 1, true,
                                            bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                            bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                            bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                            bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                            bingo[20], bingo[21], bingo[22], bingo[23], bingo[24] ),codigoTablas);
                        
                        pasa = true;
                    } else {
                        
                        pasa = false;
                        
                        do {
                            this.generarVector("B");
                            System.arraycopy(vector, 0, bingo, 0, 5);
                            this.generarVector("I");
                            System.arraycopy(vector, 0, bingo, 5, 5);
                            this.generarVector("N");
                            System.arraycopy(vector, 0, bingo, 10, 5);
                            this.generarVector("G");
                            System.arraycopy(vector, 0, bingo, 15, 5);
                            this.generarVector("O");
                            System.arraycopy(vector, 0, bingo, 20, 5);
                            if (this.numGeneradosExcepcion() >= nObligatorios) {
                                if (con.buscarTabla(bingo) != -1) {
                                    con.saveTabla(new Tabla(idx + 1, true,
                                            bingo[0], bingo[1], bingo[2], bingo[3], bingo[4],
                                            bingo[5], bingo[6], bingo[7], bingo[8], bingo[9],
                                            bingo[10], bingo[11], bingo[12], bingo[13], bingo[14],
                                            bingo[15], bingo[16], bingo[17], bingo[18], bingo[19],
                                            bingo[20], bingo[21], bingo[22], bingo[23], bingo[24] ),codigoTablas);
                                    pasa = true;
                                }
                            }
                        } while (!pasa);

                    }
                }
                
                JOptionPane.showMessageDialog(this, "Tablas Generadas", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            
                break;
        }
    }

    public void inicializar() {
        int i;
        MaxTablas = 0;
        for (i = 0; i < MAXBINGO; i++) {
            excNum[i] = 0;
        }
        for (i = 0; i < MAXWTABLA; i++) {
            wTabla[i] = 0;
        }
    }

    public void inicializarVector() {
        for (int i = 0; i < 5; i++) {
            vector[i] = 0;
        }
    }

    public int generarNumero(int de) {
        return (int) (Math.random() * 15) + de;
    }

    public void generarVector(String letra) {
        int k = 0;
        int ale = 0;
        this.inicializarVector();

        do {
            switch (letra) {
                case "B":
                    ale = this.generarNumero(1);
                    break;
                case "I":
                    ale = this.generarNumero(16);
                    break;
                case "N":
                    ale = this.generarNumero(31);
                    break;
                case "G":
                    ale = this.generarNumero(46);
                    break;
                case "O":
                    ale = this.generarNumero(61);
                    break;
            }

            if (!this.buscarNumVector(ale)) {
                vector[k] = ale;
                if (letra == "N" && k == 2) {
                    vector[k] = -1;
                }
                k++;
            }
        } while (k < MAXVECTOR);
    }

    public boolean buscarNumVector(int n) {
        boolean enc = false;
        int i;
        for (i = 0; i < MAXVECTOR; i++) {
            if (vector[i] == n) {
                enc = true;
            }
        }
        return (enc);
    }

    public boolean validarExcepciones() {
        boolean ret = true;
        for (int i = 0; i < MAXBINGO; i++) {
            for (int j = 0; j < MAXBINGO; j++) {
                if (this.bingo[i] == this.excNum[j] && this.excNum[j] != 0) {
                    ret = false;
                }
            }
        }
        return ret;
    }

    public int numGeneradosExcepcion() {
        int ret = 0;
        for (int i = 0; i < MAXBINGO; i++) {
            for (int j = 0; j < MAXBINGO; j++) {
                if (this.bingo[i] == this.excNum[j]) {
                    ret++;
                }
            }
        }
        return ret;
    }

    public boolean buscarVectorEnTablas(int[] vec) {
        boolean ret = true;
        int cnt = 0;
        for (int i = 0; i < this.MaxTablas; i++) {
            for (int j = 0; j < MAXBINGO; j++) {
                if (Tablas[i][j] == vec[j]) {
                    cnt++;
                }
            }
        }
        if (cnt < MAXBINGO) {
            ret = false;
        }
        return ret;
    }

   
    


}
