/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Bingo;
import Controlador.Licencia;
import Controlador.AccessFile;
import Modelo.Configuracion;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author oracle
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
        private Bingo con;
        private Pantalla wPantalla;

    
    public Entrada() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        con = new Bingo();
        con.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        btn_Entrar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTRASEÑA");

        passField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passField.setText("jPasswordField1");

        btn_Entrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_Entrar.setText("Entrar");
        btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Entrar)
                    .addComponent(btn_Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarActionPerformed
            try {
                // TODO add your handling code here:

                if (!con.autenticar("Pantalla", this.passField.getText())) {
                    System.out.println("Error Autenticacion ");
                } else {
                    System.out.println("Autenticacion Correcta");
                    this.setVisible(false);
                    wPantalla = new Pantalla();

                    // Modo "partida programada": si existe /Bingo/db/config.dat,
                    // se carga la configuracion binaria y se activa el amaño de
                    // cartones pre-fijados. Sin el archivo, juego normal en vivo.
                    File fCfg = new File(AccessFile.getRutaFileDB() + "config.dat");
                    if (AccessFile.buscarFile(fCfg)) {
                        wPantalla.setModoProgramado(true);
                        AccessFile.leerFileTablas(fCfg);

                        Configuracion conf1 = AccessFile.getConf(AccessFile.buscarRegistro(1));
                        if (conf1 != null && conf1.getIntento() > 0) {
                            wPantalla.setIteracion(conf1.getIntento());
                            wPantalla.setmsgJuego(conf1.getJuego());
                            wPantalla.setcodTabla1(conf1.getTabla1());
                            wPantalla.setcodTabla2(conf1.getTabla2());
                            wPantalla.setcodTabla3(conf1.getTabla3());
                        }

                        Configuracion conf2 = AccessFile.getConf(AccessFile.buscarRegistro(2));
                        if (conf2 != null) {
                            wPantalla.setTablas(conf2.getTabla1(), conf2.getTabla2(), conf2.getTabla3());
                        }

                        // Registros 3..18 -> SetConfigLetra(1..16)
                        for (int r = 3; r <= 18; r++) {
                            Configuracion c = AccessFile.getConf(AccessFile.buscarRegistro(r));
                            if (c != null) {
                                wPantalla.SetConfigLetra(r - 2, c.getIntento(), c.getTabla1(), c.getTabla2());
                            }
                        }

                        AccessFile.cerrar();
                    }

                    wPantalla.setLocationRelativeTo(this);
                    wPantalla.setVisible(true);
                    }
                    } catch (SQLException | IOException ex) {
                Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
            }
            

    }//GEN-LAST:event_btn_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Modo interno de KernelClic: generador de claves (lanzar con --keygen).
        for (String a : args) {
            if ("--keygen".equalsIgnoreCase(a)) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() { mostrarGeneradorClave(); }
                });
                return;
            }
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Puerta de seguridad: solo corre en equipos activados.
                if (!asegurarLicencia()) { System.exit(0); return; }
                try {
                    new Entrada().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // =====================================================================
    // Seguridad: activación atada al equipo (node-lock)
    // =====================================================================

    private static boolean asegurarLicencia() {
        if (Licencia.estaActivado()) return true;
        while (true) {
            String id = Licencia.idEquipo();
            javax.swing.JTextField tfClave = new javax.swing.JTextField(24);
            javax.swing.JTextField tfId = new javax.swing.JTextField(id);
            tfId.setEditable(false);
            tfId.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            tfId.setOpaque(false);
            tfId.setFont(tfId.getFont().deriveFont(java.awt.Font.BOLD));
            javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
            c.insets = new java.awt.Insets(4, 6, 4, 6);
            c.anchor = java.awt.GridBagConstraints.WEST;
            c.fill = java.awt.GridBagConstraints.HORIZONTAL;
            c.gridx = 0; c.gridy = 0; c.gridwidth = 2;
            panel.add(new javax.swing.JLabel("<html>Este equipo no está activado.<br>"
                    + "Entregue el <b>ID de equipo</b> a KernelClic para obtener su clave.</html>"), c);
            c.gridwidth = 1;
            c.gridx = 0; c.gridy = 1; panel.add(new javax.swing.JLabel("ID de equipo:"), c);
            c.gridx = 1; c.gridy = 1; panel.add(tfId, c);
            c.gridx = 0; c.gridy = 2; panel.add(new javax.swing.JLabel("Clave de activación:"), c);
            c.gridx = 1; c.gridy = 2; panel.add(tfClave, c);
            int opcion = javax.swing.JOptionPane.showConfirmDialog(null, panel,
                    "Activación del aplicativo — KernelClic",
                    javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);
            if (opcion != javax.swing.JOptionPane.OK_OPTION) return false;
            if (Licencia.activar(tfClave.getText())) {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "Equipo activado correctamente.", "Listo",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return true;
            }
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Clave incorrecta para este equipo. Verifique e intente de nuevo.",
                    "Activación fallida", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private static void mostrarGeneradorClave() {
        final javax.swing.JTextField tfId = new javax.swing.JTextField(24);
        final javax.swing.JTextField tfClave = new javax.swing.JTextField(28);
        tfClave.setEditable(false);
        javax.swing.JButton btnGen = new javax.swing.JButton("Generar clave");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                tfClave.setText(Licencia.generarClaveDesdeId(tfId.getText()));
            }
        });
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints c = new java.awt.GridBagConstraints();
        c.insets = new java.awt.Insets(4, 6, 4, 6);
        c.anchor = java.awt.GridBagConstraints.WEST;
        c.fill = java.awt.GridBagConstraints.HORIZONTAL;
        c.gridx = 0; c.gridy = 0; panel.add(new javax.swing.JLabel("ID de equipo del cliente:"), c);
        c.gridx = 1; c.gridy = 0; panel.add(tfId, c);
        c.gridx = 1; c.gridy = 1; panel.add(btnGen, c);
        c.gridx = 0; c.gridy = 2; panel.add(new javax.swing.JLabel("Clave de activación:"), c);
        c.gridx = 1; c.gridy = 2; panel.add(tfClave, c);
        javax.swing.JFrame f = new javax.swing.JFrame("Generador de Claves — KernelClic (uso interno)");
        f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        f.add(panel);
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables
}
