/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Controlador.AccessFile;
import Controlador.AccessFile;
import Controlador.Conector;
import Modelo.Configuracion;
import Modelo.Tabla;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author oracle
 */
public class Config02 extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    static final int MAXTABLAS = 10000;
    static final int MAXEXCEPCIONES = 25;
    static final int MAXBINGO = 25;
    static final int MAXWTABLA = 4;
    static final int MAXVECTOR = 5;


    private int MaxTablas;
    private int nObligatorios;
    private int codigoTablas = 1;
    private int[] excNum;
    private int[] wTabla;
    private int[] vector;
    private int[] bingo;
    private int[] bingo_w;

    private int[] tmpWtabla;

    private int[][] Tablas;

    private Conector con;

    public Config02() throws IOException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        jTablasE.removeAll();
        jTablas.removeAll();
        configuracionInicial();
        rangoTablas();

    }

    private void rangoTablas() throws SQLException, IOException {
        //Tabla t = new Tabla();
        // El ResultSet se cierra SIEMPRE: mientras viva mantiene un lock de
        // lectura en SQLite que bloquea el borrado de tablas (SQLITE_BUSY).
        try (ResultSet r = con.cargarTablas()) {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"No. Tabla", "Codigo"});

            DefaultTableModel mod2 = (DefaultTableModel) jTablasE.getModel();
            mod2.setColumnIdentifiers(new Object[]{"No. Tabla", "Codigo"});

            while (r.next()) {
                /*t.setNumTabla(r.getInt("numTabla"));
                    t.setCodigo(r.getString("codigo"));
                 */
                modelo.addRow(new Object[]{r.getInt("numTabla"), r.getString("codigo")});
                jTablas.setModel(modelo);

            }
            jTablasE.removeAll();

        }
    }

    private void configuracionInicial() throws IOException {
        int i, j;
        con = new Conector();
        con.connect();
        MaxTablas = 0;
        excNum = new int[MAXEXCEPCIONES];
        for (i = 0; i < MAXEXCEPCIONES; i++) {
            excNum[i] = 0;
        }
        wTabla = new int[MAXWTABLA];
        for (i = 0; i < MAXWTABLA; i++) {
            wTabla[i] = 0;
        }
        vector = new int[MAXVECTOR];
        for (i = 0; i < MAXVECTOR; i++) {
            vector[i] = 0;
        }
        bingo = new int[MAXBINGO];
        for (i = 0; i < MAXBINGO; i++) {
            bingo[i] = 0;
        }
        bingo_w = new int[MAXBINGO];
        for (i = 0; i < MAXBINGO; i++) {
            bingo_w[i] = 0;
        }   /*
        Tablas = new int[this.][MAXBINGO+1];
        for ( i=0; i<MAXTABLAS; i++ )
        for ( j=0; j<MAXBINGO+1; j++ )
        Tablas[i][j]=0;
        */
        if (!AccessFile.buscarFile(new File(AccessFile.getRutaFileDB() + "tablas.db"))
                //|| !AccessFile.validarLic(new File(AccessFile.getRutaFileDb()),"C")
                ) {
            System.out.print("Error de Conexion a Base de Datos");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.ButtonGroup();
        BingoCodificacion = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        btn_updPassword = new javax.swing.JButton();
        btn_updPassword.setVisible(false); // password change removed en Universal
        btn_SalirGenerador = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTabla06 = new javax.swing.JTextField();
        txtTabla04 = new javax.swing.JTextField();
        txtTabla05 = new javax.swing.JTextField();
        btnGenerar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablas = new javax.swing.JTable();
        pasarAeliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablasE = new javax.swing.JTable();
        eliminarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar");
        setName("Configurar"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btn_updPassword.setText("Cambiar Contraseña");
        btn_updPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updPasswordActionPerformed(evt);
            }
        });

        btn_SalirGenerador.setText("Salir");
        btn_SalirGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirGeneradorActionPerformed(evt);
            }
        });

        jLabel8.setText("Tablas Ganadoras");

        txtTabla06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTabla06ActionPerformed(evt);
            }
        });

        txtTabla04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTabla04ActionPerformed(evt);
            }
        });

        txtTabla05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTabla05ActionPerformed(evt);
            }
        });

        btnGenerar1.setText("Cargar ");
        btnGenerar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_SalirGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtTabla04, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTabla05, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTabla06, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_updPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTabla04, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTabla05, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTabla06, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerar)
                    .addComponent(btn_SalirGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(304, 304, 304))
        );

        jTabbedPane1.addTab("Configuracion Inicial", jPanel3);

        jTablas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablas);

        pasarAeliminar.setText("Pasar");
        pasarAeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarAeliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos Originales");

        jLabel2.setText("Datos a Eliminar");

        jTablasE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablasE);

        eliminarDatos.setText("Eliminar");
        eliminarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pasarAeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(eliminarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(pasarAeliminar)
                                .addGap(93, 93, 93)
                                .addComponent(eliminarDatos)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rangos de Tablas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        con.close();
    }//GEN-LAST:event_formWindowClosed

    private void btnGenerar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerar1ActionPerformed
        try {
            // TODO add your handling code here:
            AccessFile.cargarPartida();

            // Sin partida guardada no hay nada que cargar: avisar en vez de
            // reventar con NullPointerException al leer un registro ausente.
            if (AccessFile.getNumeroRegistros() == 0) {
                JOptionPane.showMessageDialog(this,
                        "No hay una partida guardada todavia.\n"
                        + "Configure los valores y presione Generar para crearla.",
                        "Sin configuracion", JOptionPane.INFORMATION_MESSAGE);
                return;
            }


            Configuracion conf2 = AccessFile.getConf(AccessFile.buscarRegistro(2));
            txtTabla04.setText(conf2.getTabla1());
            txtTabla05.setText(conf2.getTabla2());
            txtTabla06.setText(conf2.getTabla3());
            AccessFile.cerrar();
        } catch (IOException ex) {
            Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerar1ActionPerformed

    private void txtTabla05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTabla05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTabla05ActionPerformed

    private void txtTabla04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTabla04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTabla04ActionPerformed

    private void txtTabla06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTabla06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTabla06ActionPerformed

    private void btn_SalirGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirGeneradorActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirGeneradorActionPerformed

    private void btn_updPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updPasswordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_updPasswordActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String tabla4 = txtTabla04.getText().trim().isEmpty() ? "-1" : txtTabla04.getText().trim();
        String tabla5 = txtTabla05.getText().trim().isEmpty() ? "-1" : txtTabla05.getText().trim();
        String tabla6 = txtTabla06.getText().trim().isEmpty() ? "-1" : txtTabla06.getText().trim();

        try {
            AccessFile.nuevaPartida();
            AccessFile.añadirConf(new Configuracion(1, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(2, 0, "N/A", tabla4, tabla5, tabla6));
            AccessFile.añadirConf(new Configuracion(3, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(4, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(5, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(6, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(7, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(8, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(9, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(10, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(11, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(12, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(13, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(14, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(15, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(16, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(17, 0, "N/A", "N/A", "N/A", "N/A"));
            AccessFile.añadirConf(new Configuracion(18, 0, "N/A", "N/A", "N/A", "N/A"));
            
            

  
            
            
            AccessFile.cerrar();
            JOptionPane.showMessageDialog(this, "El registro se realizó correctamente.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error en la escritura de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void eliminarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDatosActionPerformed

        if (jTablas.getSelectedRow() == -1) {
            return;
        }

        //Eliminar las filas Seleccionadas
        TableModel mod2 = jTablasE.getModel();
        jTablasE.selectAll();
        int[] filas = jTablasE.getSelectedRows();
        Object[] row = new Object[2];

        for (int i = 0; i < filas.length; i++) {
            row[0] = mod2.getValueAt(filas[i], 0); //NumTabla
            int numTabla = (row[0] == null ? -1 : (int) row[0]);

            try {
                con.borrarTabla(numTabla);

                // LLamar eliminar de la base de datos
                // mod2.addRow(row);
            } catch (IOException ex) {
                Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        jTablasE.removeAll();
        jTablas.removeAll();

        try {
            rangoTablas();
        } catch (SQLException ex) {
            Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eliminarDatosActionPerformed

    private void pasarAeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarAeliminarActionPerformed
        // TODO add your handling code here:

        TableModel mod1 = jTablas.getModel();
        int[] filas = jTablas.getSelectedRows();
        Object[] row = new Object[2];

        DefaultTableModel mod2 = (DefaultTableModel) jTablasE.getModel();

        for (int i = 0; i < filas.length; i++) {
            row[0] = mod1.getValueAt(filas[i], 0);
            row[1] = mod1.getValueAt(filas[i], 1);
            mod2.addRow(row);
        }

    }//GEN-LAST:event_pasarAeliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BingoCodificacion;
    private javax.swing.ButtonGroup Juego;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGenerar1;
    private javax.swing.JButton btn_SalirGenerador;
    private javax.swing.JButton btn_updPassword;
    private javax.swing.JButton eliminarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablas;
    private javax.swing.JTable jTablasE;
    private javax.swing.JButton pasarAeliminar;
    private javax.swing.JTextField txtTabla04;
    private javax.swing.JTextField txtTabla05;
    private javax.swing.JTextField txtTabla06;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //con = new Conector();
        //</editor-fold>
        //</editor-fold>
        //con = new Conector();

        // Create and display the form 
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Config02().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Config02.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

}
